name: Run on main, or merge to main

on:
  push:
    branches:
      - main

jobs:
  dumps:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GSHA: ${{ github.sha }}
        run: |
          echo "$GSHA"
          echo "$GITHUB_SHA"
          echo "$GITHUB_CONTEXT"
