name: Run on PR merges

on:
  pull_request:
    types:
      - closed
    braches:
      - main

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
