name: Run on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  dumps:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: test/app
          tags: |
            type=sha,format=long,prefix={{branch}}-
            type=ref,event=pr

      - name: Print extracted metadata
        env:
          META: ${{ toJson(steps.meta.outputs) }}
        run: echo "$META"
